# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.cache/wt [current_project]
set_property parent.project_path C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/oskar/Downloads/picoblaze_uart/baud_rate_clock.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/Downloads/embedded_kcpsm6.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/Downloads/kcpsm6.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Desktop/spi_adxl345/modulo_spi.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/oskar/Downloads/picoblaze_uart/modulo_uart.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Desktop/spi_adxl345/pmod_accelerometer_adxl345.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/oskar/Downloads/puerto_7segmentos/puerto_7segmentos.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/picoblaze_puertos/puerto_salida_leds.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/oskar/Desktop/picoblaze_puertos/registro_puerto_entrada.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Desktop/spi_adxl345/spi_master.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/oskar/Downloads/picoblaze_uart/uart_rx6.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/oskar/Documents/vivado/Act5.1/Act5.1.srcs/sources_1/imports/oskar/Downloads/picoblaze_uart/uart_tx6.vhd
  C:/Users/oskar/Desktop/Reto_DiseñoLogicaProgramable/kcpsm6/your_program.vhd
  C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/sources_1/imports/Reto_DiseñoLogicaProgramable/top-level.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/constrs_1/imports/Downloads/Arty-A7-35-Master.xdc
set_property used_in_implementation false [get_files C:/Users/oskar/Documents/vivado/hollow_knight/hollow_knight.srcs/constrs_1/imports/Downloads/Arty-A7-35-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
